baseurl = "/"
languageCode = "en-us"
title = "Matt Freitas"
theme = "hugo-theme-nix"

[params]
  GithubID = "chupacabreh"
  TwitterID = "your_twitter"
  LinkedInID = "matthew-freitas"
  FacebookID = "matthew.freitas"
  Name = "your_name"
  HeaderUsername = "username"
  HeaderHostname = "hostname"
  Email = "mattfreitas415@gmail.com"
  About = "info_about_you"
  ProfilePicture = "https://pbs.twimg.com/profile_images/485564678039302144/Fjxv6IbQ.png"
  GoogleAnalytics = "your_google_analytics_id"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/post"
